"""Initial version

Revision ID: 9654503ffceb
Revises:
Create Date: 2018-09-20 09:26:31.583960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9654503ffceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.TEXT(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.TEXT(), nullable=False),
    sa.Column('car', sa.TEXT(), nullable=False),
    sa.Column('company_name', sa.TEXT(), nullable=False),
    sa.Column('company_address', sa.TEXT(), nullable=False),
    sa.Column('price', sa.Float(precision=2, asdecimal=True), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
